export default () => ({
  port: parseInt(process.env.PORT || '3000', 10),
  mongoUri: process.env.MONGO_URI,
  jwt: {
    adminSecret: process.env.ADMIN_JWT_SECRET,
    userSecret: process.env.USER_JWT_SECRET,
    expiresIn: process.env.JWT_EXPIRES_IN || '1h',
  },
  bcryptSaltRounds: parseInt(process.env.BCRYPT_SALT_ROUNDS || '12', 10),
  cashfreeAppId: process.env.CASHFREE_APP_ID,
  cashfreeSecretKey: process.env.CASHFREE_SECRET_KEY,
  frontendBase: process.env.FRONTEND_BASE,
  apiBase: process.env.API_BASE,
  GA4_PROPERTY_ID: process.env.GA4_PROPERTY_ID,
  GA4_SERVICE_ACCOUNT_KEY: process.env.GA4_SERVICE_ACCOUNT_KEY,
  GA4_SERVICE_ACCOUNT_KEY_FILE: process.env.GA4_SERVICE_ACCOUNT_KEY_FILE,
  resendApiKey: process.env.RESEND_API_KEY,
  resendFromEmail: process.env.RESEND_FROM_EMAIL,
  mgmNotificationEmail: process.env.MGM_NOTIFICATION_EMAIL,
  seedAdminSecret: process.env.SEED_ADMIN_SECRET,
});
